<?php
namespace LaraModel\Console\Commands;
use Illuminate\Filesystem\Filesystem;

//class MakeModel extends \LaraMaker\Console\Commands\LaraClassMaker
class MakeModel
{

//    /**
//     * The name and signature of the console command.
//     *
//     * @var string
//     */
//    protected $name = 'lara-model:make';
//
////    protected $appRootPath = 'Models';
//
//    protected $parent = 'LaraModel\Models\LaraModel';
//
//    protected $makeBaseClass = true;
//
//    protected $type = 'Model';
//
//    protected $stubPath;
//    /**
//     * The console command description.
//     *
//     * @var string
//     */
//    protected $description = 'Command description';
//
//    /**
//     * MakeModel constructor.
//     */
//    public function __construct(Filesystem $files)
//    {
//        parent::__construct($files);
//
//    }
//
//    public function configure()
//    {
//        parent::configure(); // TODO: Change the autogenerated stub
//    }
//
////    /**
////     * Execute the console command.
////     *
////     * @return mixed
////     */
////    public function handle()
////    {
////        $this->makeBasedConfig();
////    }
//
//    public function makeBasedConfig()
//    {
//        $models = config('lara_model.models');
//        foreach ($models as $model) {
//            $fillable = $this->getFillable($model);
//            dd($fillable );
//        }
//    }
//
//    protected function getFillable($model)
//    {
//        if (!empty($model['fillable'])) {
//            return $model['fillable'];
//        }
//
//        if (!empty($model['migration'])) {
//            $fillable = array_keys($model['migration']);
//            unset($fillable[array_search('id', $fillable)]);
//            return $fillable;
//        }
//
//        return [];
//    }

}